name: Playwright + Cucumber Tests on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install

    - run: npx playwright install --with-deps

    - run: npm run test:chrome

    - run: npm run test:api

    - run: node generate-report.js

    - run: npm run report:api

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-playwright-reports
        path: |
          reports/
          reports/api/
          reports/cucumber_report.html
          reports/cucumber_report.json